### ISSUE TITLE
Intake Task -- Molly

### ISSUE THREAD

**Issue by DavidRitzwoller** [mollywharton/template#1]
# Practice Task 

### Checklist 

* Read through [RA manual](https://github.com/gslab-econ/ra-manual) carefully.
* Set up your computer properly using the [computer build sheet](https://github.com/gslab-econ/admin/blob/9e5bafed3119856ed2cbf872f58edc4184f12c60/computer-build-sheet/package_build.sh) and Homebrew per RA manual. 

### Task Description

Make sure you follow all procedures in the RA manual (e.g., issue threads, branching, and [time tracking](https://github.com/gslab-econ/admin/wiki/Time-Tracking)).

* Create your own public repository from the [lab template](https://github.com/gslab-econ/template).
* Modify the code to execute `analysis/source/prepare_data/create_data.r`. Run and commit.
* Modify the code to execute `analysis/source/prepare_data/create_data.do`. Run and commit.
* Load external raw data from this [Dropbox directory](https://www.dropbox.com/sh/z694st8vyuwp1o4/AAAKYQmEJIMN5Cmws0N2mbJWa?dl=0) into `analysis` following the guidelines in the template.
* Modify the code so that targets in `analysis/build/descriptive` use the data from Dropbox.
* Modify the code in `paper_slides` to use the new output of `analysis`.
* Run all the code in `analysis` and `paper_slides` and commit. 
* Complete the task. Invite the practice task assigner as a collaborator on your GitHub repo and ask them for peer review.

**Comment by DavidRitzwoller** [comment]
## General tasks

- [x] Have user enable two-step authentication SSH Key for GitHub (Two-factor authentication)
- [x] Have user set GitHub profile picture
- [x] Determine computing resources
- [x] Set up individual RA notebooks
- [x] Update GSLAB Personnel

## Permissions

- [x] SUNetID
- [x] SVN (waiting for help ticket to go through)
- [x] JIRA/Confluence
- [x] GitHub
- [x] hsfiles
- [x] Sherlock 
- [x] Evernote (request sent)
- [x] Everhour (request sent)
- [x] Google Calendar
- [x] Dropbox

## Workflow

- [x] Practice task
- [x] Setup local computer according to build sheet

**Comment by DavidRitzwoller** [comment]
# Computer Build Sheet

Note: (+) following an entry below indicates that the application should be added to the path so it can be started from the command line / terminal. Please test this for each application before completing build.

Note: Files references below (profile.do, startup.m, etc. will be provided separately)

## All Machines (Mac & PC)

### Application Software

* Microsoft Office
* Acrobat Professional
* Chrome
    - Install Evernote Web Clipper
* GitHub
* Google Drive and gdrive
   - Enter `gdrive about` at the command line just after installing the gdrive. Follow gdrive's instructions and ensure that the email account through which you have access to the GSLab Google Drive folders.
   - If the homebrew installation of gdrive does not work, follow the instructions [here](https://github.com/gslab-econ/admin/blob/7336a6b40b3a6d81ded2855c76aea58cb75bf1eb/issues/gdrive-77/gdrive-77.md).
* Evernote
* Skype
* Dropbox
* Microsoft Remote Desktop
* Stata MP4 (+)
* Matlab (+)
  - Include statistics, optimization, and parallel computing toolboxes
* Mathematica (+)
* R (+)
* Python 2.X (+)
  - Preinstalled on Mac OSX but upgrade to latest 2.X version. Do not install 3.X.
* Lyx (+)
* Knitro

### Stanford Utility Software (Stanford Machines Only)

* Stanford Desktop Tools
* BigFix Client
* Sophos Anti-Virus
* Stanford Open AFS
* Kerberos

### Other Instructions

* For desktops, please assign a static IP address
* Additional Matlab setup
  - Add file “startup.m” to “%MATLAB%/toolbox/local/” where %MATLAB% is the path to the root Matlab directory.
* Additional Stata setup
  - Add profile.do to the directory containing the Stata executable.
* Additional Lyx setup
  - Add file “text.module” to “%PATHTOLYXBINARIES%\layouts” (Windows) or “~/.lyx/layouts” (Mac)

## Mac Only

### Application Software

* FileVault2 Encryption
* CyberDuck
* Fetch
* Magnet (window shortcut utility)
* Dashlane (password manager)
* Cornerstone SVN Client
* MacGhostView
* Sublime Text
  - Make default editor for .txt files
  - Install Package Manager
  - Install Markdown Preview and Sublimerge Pro packages
  - Replace contents of Sublime Text->Preferences->Settings - User with sublime-text-settings.txt

### Other Instructions

* Ensure that your Google Drive folder lives in your home directory (its path should be `"$HOME/Google Drive"`).

## Windows Only
### Application Software

* Notepad++
    - Import file userdefineLang_stata.xml using User Defined Dialogue
* PuTTY
* SecureFX
* ExamDiff
* GrepWin
* Tortoise SVN
	- Include command line client
* Ghostview
* GSView
* RTools

### Additional Instructions 

* Add a system environment variable called "gslab_make_path" with value "https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/python/gslab_make/"
* Add a system environment variable called "STATAEXE" with value equal to the name of the Stata executable on the machine (e.g., "StataMP-64.exe")
* Add ".PL" and ".PY" to PATHEXT
